//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChurchMgtEntities : DbContext
    {
        public ChurchMgtEntities()
            : base("name=ChurchMgtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Church> Churches { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Offering> Offerings { get; set; }
        public virtual DbSet<SpecialContr> SpecialContrs { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Tithe> Tithes { get; set; }
        public virtual DbSet<CategoryExpens> CategoryExpenses { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
    }
}
